variable "vpc_id" {}
variable "my_ip" {}
variable "env_prefix" {}
variable "image_name_filter" {}
variable "public_key_location" {}
variable "instance_type" {}
variable "public_subnet_id" {}
variable "avail_zone" {}
variable "keyName" {}
variable "entry_script_location" {}